config/routes.rb
Rails.application.routes.draw do

  get 'landing/show'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :courses do
      collection do
          get "/search" => "search#index", as:"search"
          get "/search_results" => "search#show_results", as:"search_results"
          get '/enroll/:course' => 'search#enroll', as: :enroll
      end
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'landing#show'

  get "/instructors" => "instructors#index"
  get "/subjects" => "subjects#index"
  get "/courses" => "courses#index"
  get "/account" => "account#index"

end

app/models/course.rb
class Course < ActiveRecord::Base

    has_and_belongs_to_many :users
end

app/models/courses_user.rb
class CoursesUser < ActiveRecord::Base

    belongs_to :course
    belongs_to :user

    validates_uniqueness_of :user_id, :scope => :course_id
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_and_belongs_to_many :courses

end

app/controllers/account_controller.rb
class AccountController < ApplicationController

    def index
        @user = current_user
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

  def show

  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController


  def index
    @courses = Course.all
  end

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end
  
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def show
    if not signed_in?
        redirect_to "/sign_in"
    else
        @enrolled_classes_objects = CoursesUser.where(user_id: current_user.id)
        @list_of_enrolled_courses = Array.new

        @enrolled_classes_objects.each do |object|
            @list_of_enrolled_courses.push(Course.find_by(id: object.course_id))
        end
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
require 'json'
    def index
      @subjects = Subject.all
    end

    def show_results
        @courses=Course.where("name LIKE ?", "%#{params[:name]}%")

        subject_id = params[:subject_id].to_s.split "=>"
        subject_id = subject_id[1].split "}"
        subject_id = subject_id[0].to_s
        @search_results= Array.new
        #Iterate through courses to narrow results to courses with correct subject id
        @courses.each do |course|
          subjects = course.subjects
          #separate each subject this course is included in
          subjects = subjects.split "}"

          subjects.each do |subject|
            #pull out subject id from subject data
            data = subject.split ","
            data.each do |section|

              if section.to_s.include? "id"
                #pull out id number
                id_number = section.split "=>"
                id_number = id_number[1].to_s

                if subject_id == id_number
                  #prevent duplicate courses
                  if not @search_results.include? course
                      @search_results.push course
                  end
                end
              end
            end
          end
        end

        if not @search_results.empty?
          @courses = @search_results
        end

        respond_to do |format|
          format.js
        end
        
    end

    def enroll
        enrollment = CoursesUser.new
        course = params[:course]
        enrollment.course_id = course
        enrollment.user_id = current_user.id
        enrollment.save
        redirect_to "/"
    end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController


  def index
    @subjects = Subject.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/courses/index.html.erb
<h1>Listing Courses</h1>

<table class="table table-bordered">
    <tr>
      <th>Course Code</th>
      <th>Name</th>
      <th>Description</th>
    </tr>
    <% @courses.each do |course| %>
      <tr>
          <td><%=course.code%></td>
          <td><%=course.name%></td>
          <td><%=course.description%></td>
      </tr>
    <% end %>
</table>

app/views/instructors/index.html.erb
<h1>Listing Instructors</h1>

<table class="table table-bordered">
    <tr>
      <th>Name</th>
      <th> Email </th>
      <th> Comment </th>
    </tr>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%=instructor.first + " " + instructor.last%></td>
        <td><%=instructor.email%></td>
        <td><%=instructor.comment%></td>
      </tr>
    <% end %>
</table>

app/views/landing/show.html.erb
<h1>User Email</h1>

<h3><%=current_user.email%></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <%= javascript_include_tag 'application' %>
        <%= csrf_meta_tag %>

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    </head>
    <body>
        <div id="main-container" class="container-fluid">


<nav class="navbar navbar-default">
  <div class="container-fluid">



    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <% if signed_in? %>
                <li>
                    <%= link_to "Homepage", "/", method: :get%>
                </li>
                <li>
                    <%= link_to "Instructor List", "/instructors", method: :get%>
                </li>
                <li>
                    <%= link_to "Course List", "/courses", method: :get%>
                </li>
                <li>
                    <%= link_to "Course Search", "/courses/search", method: :get%>
                </li>
                <li>
                    <%= link_to "Subject List", "/subjects", method: :get%>
                </li>
            <%end%>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li>
                <% if signed_in? -%>
                    <%= button_to t(".sign_out"), sign_out_path,class: "btn btn-danger navbar-btn", method: :delete %>
                <% else -%>
                    <%= link_to t(".sign_in"), sign_in_path %>
                <% end -%>
            </li>
        </ul>
    </div>
</nav>
            <%= yield %>
        </div>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    </body>
</html>

app/views/search/_results.html.erb
<!---<%= button_to'New Search', search_courses_path, class: "btn btn-success", method: :get%>-->

<table class="table table-bordered">
    <tr>
      <th>Course Code</th>
      <th>Name</th>
      <th>Description</th>
    </tr>
    <% @courses.each do |course| %>
      <tr>
          <td><%=course.code%></td>
          <td><%=course.name%></td>
          <td><%=course.description%></td>
          <td>
              <%= button_to 'Enroll', enroll_courses_path(course.id), class: "btn btn-success", method: :get%>
          </td>
      </tr>
    <% end %>
</table>

app/views/search/index.html.erb
<h1>Search for Courses</h1>

<%= form_tag(search_results_courses_path, method: "get", class: "form", remote: true) do %>

  <div class="form-group">
    <label>Course Name</label>
    <%= text_field_tag(:name, value ="",class: "form-control",  onkeyup:"submitFromAjax();") %>
  </div>

  <div class="form-group">
    <label>Subject</label>

    <%= select(:subject_id, "subject_id", Subject.all.collect {|subject| [ subject.name, subject.subject_id ] }, {include_blank: 'Any'}, class: "form-control", onchange:"submitFromAjax();") %>

  </div>



  <!--<%= submit_tag("Search", class: "btn btn-success") %> -->
<% end %>
<br/>
<div id="results">

</div>

app/views/search/show_results.js.erb
$('#results').html("<%= escape_javascript (render(partial: 'results')) %>");

app/views/subjects/index.html.erb
<h1>Listing Subjects</h1>

<table class="table table-bordered">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Abbreviation</th>
      <th>Term</th>
    </tr>
    <% @subjects.each do |subject| %>
      <tr>
          <td><%=subject.subject_id%></td>
          <td><%=subject.name%></td>
          <td><%=subject.abbreviation%></td>
          <td><%=subject.term%></td>

      </tr>
    <% end %>
</table>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>